FROM registry.fedoraproject.org/fedora-toolbox:latest

COPY root /

RUN dnf upgrade -y && \
    dnf install -y codium golang meson openssl-devel pnpm && \
    curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/usr sh

# don't clean up dnf metadata since distrobox is almost guaranteed to want to install something
# and the image is built so regularly (thanks micro$oft) that it doesn't expire
