# SPDX-FileCopyrightText: 2024 Daniel Foster <daniel@amesite.me>
#
# SPDX-License-Identifier: CC0-1.0

matrix:
  image:
    - distrobox

when:
  - event: push
    branch: main
  - event: cron
    cron: build-oci

steps:
  - name: publish
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      # I'm using ghcr as to not waste Codeberg's infra
      repo: ghcr.io/applemayexist/${CI_REPO_NAME}
      registry: ghcr.io
      username: applemayexist
      password:
        from_secret: gh_token
      context: ${image}
      dockerfile: ${image}/Containerfile
      platforms: linux/amd64
