name: Create and publish container image(s)

on:
  push:
  schedule:
    - cron: 0 0 * * 0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - toolbx
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mkosi
        uses: systemd/mkosi@v25.3

      - name: Install other dependencies
        run: sudo apt install -y libarchive-tools

      - name: Build image
        run: |
          cd ${{ matrix.image }}
          mkosi -f
          bsdtar --strip-components=2 -c mkosi.output/${{ matrix.image }} | podman image load

      - name: Push to ghcr.io
        if: ${{ github.ref_name == 'main' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
