name: Create and publish a Docker image

on:
  push:
    branches:
      - main
  schedule:
    # dnf metadata (fedora-updates and vscodium) expires every 6 hours
    - cron: 0 */6 * * *

jobs:
  build-and-push-image:
    strategy:
      matrix:
        image:
          - distrobox
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner}}/${{ matrix.image }}:latest
