name: Create and publish container image(s)

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - distrobox
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          context: ${{ matrix.image }}
          containerfiles: ${{ matrix.image }}/Containerfile

      - name: Push to ghcr.io
        if: ${{ github.ref_name == 'main' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
